AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  timing-overview-lambda
Globals:
  Function:
    Timeout: 5

Parameters:
    ApiTokenParameterPath:
      Type: String
      Description: The path of the parameter store secret containing the Timing API token (don't include the starting /)
      Default: timing/api-token

Resources:
  TimingGraphAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - "*~1*"
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage Plan for Timing API
          Quota:
            Limit: 500
            Period: MONTH
          Throttle:
            BurstLimit: 5
            RateLimit: 2
  TimingGraphAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /graph
            Method: POST
            RestApiId: !Ref TimingGraphAPI
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ApiTokenParameterPath
      Environment:
        Variables:
          API_TOKEN_PARAMETER: !Sub "/${ApiTokenParameterPath}"

Outputs:
  Endpoint:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${TimingGraphAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/graph"
