on: push
name: Build and Deploy
jobs:
  build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install dependencies
        run: |
          cd src
          go get -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: src

      - name: Run tests
        run: |
          cd src
          go test ./...

      - name: Build verification
        run: |
          cd src
          GOOS=linux GOARCH=amd64 go build -o ../timing-overview main.go
