name: Release Go Binaries

on:
  release:
    types: [created]

jobs:
  release:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Release Go Binary
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./src"
          binary_name: "timing-overview"
          extra_files: LICENSE README.md
          ldflags: "-s -w"